/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package opencv;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author alian
 */
public class MorphologicalOperation extends javax.swing.JFrame {

    static BufferedImage image;
    static boolean imageLoaded = false;
    String imagePath;
    String currentImagePath = "src//opencv//images//output//fourth.png";
    /**
     * Creates new form MorphologicalOperation
     */
    public MorphologicalOperation(String imagePath) {
        
        this.imagePath = imagePath;
        initComponents();

        try {
            File f = new File(imagePath);
            BufferedImage image;
            image = ImageIO.read(f);
            writeImage(image);
            imageBoxFourthScreen.setIcon(new ImageIcon(image));
        } catch (IOException ex) {
            Logger.getLogger(FilterScreen.class.getName()).log(Level.SEVERE, null, ex);
        }

        System.out.println(this.imagePath);
        this.setLocationRelativeTo(null);
    }
    public void writeImage(BufferedImage image) throws IOException {
        File outputfile = new File(currentImagePath);
        ImageIO.write(image, "png", outputfile);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        imageBoxFourthScreen = new javax.swing.JLabel();
        acceptMorphologicalOperation = new javax.swing.JRadioButton();
        declineMorphologicalOperation = new javax.swing.JRadioButton();
        nextButtonOnFourthScreen = new javax.swing.JButton();
        backButtonOnFourthScreen = new javax.swing.JButton();
        MorphologicalOperationsCombobox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(acceptMorphologicalOperation);
        acceptMorphologicalOperation.setText("Morf. İşl. uygulamak istiyorum");

        buttonGroup1.add(declineMorphologicalOperation);
        declineMorphologicalOperation.setText("Morf. İşl. uygulamak istemiyorum");

        nextButtonOnFourthScreen.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        nextButtonOnFourthScreen.setLabel("İleri >");

        backButtonOnFourthScreen.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        backButtonOnFourthScreen.setLabel("< Geri");

        MorphologicalOperationsCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Morfolojik İşlemler", "Siyah beyaz resimde genişletme", "Siyah beyaz resimde erozyon", "Siyah beyaz resimde açma", "Siyah beyaz resimde kapama" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(acceptMorphologicalOperation)
                    .addComponent(declineMorphologicalOperation)
                    .addComponent(MorphologicalOperationsCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(imageBoxFourthScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backButtonOnFourthScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(nextButtonOnFourthScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(acceptMorphologicalOperation)
                        .addGap(33, 33, 33)
                        .addComponent(declineMorphologicalOperation)
                        .addGap(56, 56, 56)
                        .addComponent(MorphologicalOperationsCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imageBoxFourthScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backButtonOnFourthScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(nextButtonOnFourthScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MorphologicalOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MorphologicalOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MorphologicalOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MorphologicalOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MorphologicalOperation("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> MorphologicalOperationsCombobox;
    private javax.swing.JRadioButton acceptMorphologicalOperation;
    private javax.swing.JButton backButtonOnFourthScreen;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton declineMorphologicalOperation;
    private javax.swing.JLabel imageBoxFourthScreen;
    private javax.swing.JButton nextButtonOnFourthScreen;
    // End of variables declaration//GEN-END:variables
}
